name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          6.0.x
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          8.0.x 
    - run: dotnet build
    - run: dotnet test -f net6.0
    - run: dotnet test -f net8.0
